// books.js
// NOTA: category debe ser: "planlector", "novela" o "ensayo" (para que funcionen los filtros)

const books = [
  {
    id:1,
    title: "Accidental Journalist. 20 years in Peru",
    author: "Sally Bowen",
    editorial: "Peisa",
    category: "periodismoycomunicacion",
    category_display: "Periodismo y comunicación",
    price: 40.00,
    image: "img/accidental_journalist.jpg"
  }, 
  {
    id:2,
    title: "Vivir para contarla",
    author: "Gabriel García Márquez",
    editorial: "Norma",
    category: "novela",
    category_display: "Novelas",
    price: 30.00,
    image: "img/vivir_para_contarla.jpeg"
  }, 
  {
    id:3,
    title: "Un placer fugaz: correspondencia ",
    author: "Truman Capote",
    editorial: "Debolsillo",
    category: "novela",
    category_display: "Novelas",
    price: 30.00,
    image: "img/un_placer_fugaz.jpeg"
  }, 
  {
    id:4,
    title: "CoNpasión:familia, prensa y sociedad",
    author: "Jaime Vásquez Valcárcel",
    editorial: "Tierra Nueva",
    category: "cronica",
    category_display: "Crónicas",
    price: 20.00,
    image: "img/con_pasion_familia_prensa_y_sociedad.jpeg"
  }, 
  {
      id:5,
      title: "Cambio de palabras",
      author: "César Hildebrandt",
      editorial: "Tierra Nueva",
      category: "ensayo",
      category_display: "Ensayos",
      price: 40.00,
      image: "img/cambio_de_palabras.jpeg"
  }, 
  {
    id:6,
    title: "Aullido y otros poemas",
    author: "Allen Ginsberg",
    editorial: "Visor libros",
    category: "poesia",
    category_display: "Poesía",
    price: 20.00,
    image: "img/aullido_y_otros.jpeg"
  }, 
  {
    id:7,
    title: "Aquí hay icebergs",
    author: "Katya Adaui",
    editorial: "Debolsillo",
    category: "cuento",
    category_display: "Cuentos",
    price: 20.00,
    image: "img/aqui_hay_icebergs.jpeg"
  }, 
  {
    id:8,
    title: "40 éxitos en comunicación",
    author: "Asociación Española de Empresas de Ingeniería y Consultoras",
    editorial: "Prentice Hall",
    category: "marketing",
    category_display: "Marketing",
    price: 45.00,
    image: "img/40_exitos_en_comunicacion.jpeg"
  }, 
  {
    id:9,
    title: "Conversación en la catedral",
    author: "Mario Vargas Llosa",
    editorial: "Punto de Lectura",
    category: "novela",
    category_display: "Novelas",
    price: 25.00,
    image: "img/conversacion_en_la_catedral.jpeg"
  }, 
  {
    id:10,
    title: "El coronel no tiene quien le escriba",
    author: "Gabriel García Márquez",
    editorial: "Debolsillo",
    category: "novela",
    category_display: "Novelas",
    price: 20.00,
    image: "img/coronel_no_tiene.jpeg"
  }, 
  {
    id:11,
    title: "Ciudad de M",
    author: "Óscar Malca",
    editorial: "Random house",
    category: "novela",
    category_display: "Novelas",
    status: "8/10",
    availability: "En stock",
    description: "Entre pases de droga, fútbol callejero y una feroz crisis, M. vive junto a sus amigos en un territorio desvastado por la miseria, elalcohol y la violencia: la Magdalena de los años noventa. Atraviesa sus calles con hambre, sin dinero y en busca de alguna oportunidad que le dé sentido a su existencia. Piensa: «Magdalena se caerá sola, sin prisa. (...) El curso de la vida y la muerte, lo belloy el espanto en una misma cuadra». Y es en esas mismas cuadras donde M. observará el hondo vacío en el que transcurre su vida. Ciudad de M, de Oscar Malca, es una novela sobre la desolación, donde la palabra futuro escasea y el pasado es mejor no visitarlo. Este presente continuo es la única alternativa de M. y sus amigos, quienes tienen en el rock, las peleas y las drogas su único alimento. El lector hallará en este fragor hiperrealista una forma de iluminación, también cierta forma de exaltada poesía.",
    price: 15.00,
    image: "img/ciudad_de_m.jpeg"
  }, 
  {
    id:12,
    title: "Por quien doblan las campanas",
    author: "Ernest Hemingway",
    editorial: "Debolsillo",
    category: "novela",
    category_display: "Novelas",
    status: "9/10",
    availability: "En stock",
    description: "En los tupidos bosques de pinos de una región montañosa española, un grupo de milicianos se dispone a volar un puente esencial para la ofensiva republicana. La acción cortará las comunicaciones por carretera y evitará el contraataque de los sublevados. Robert Jordan, un joven voluntario de las Brigadas Internacionales, es el dinamitero experto que ha venido a España para llevar a cabo esta misión. En las montañas descubrirá los peligros y la intensa camaradería de la guerra. Y descubrirá también a María, una joven rescatada por los milicianos de manos de las fuerzas sublevadas de Franco, de la cual se enamorará enseguida.",
    price: 30.00,
    image: "img/por_quien_doblan_las_campanas.jpeg"
  }, 
  {
    id:13,
    title: "Pétronille",
    author: "Amélie Nothomb",
    editorial: "Anagrama",
    category: "novela",
    category_display: "Novelas",
    status: "7.5/10",
    availability: "En stock",
    description: "Disponer de un buen compañero de borrachera es un asunto muy serio. Aficionada al champán, Amélie Nothomb encuentra a la camarada ideal de manera imprevista en una librería donde ha sido invitada a firmar ejemplares de El sabotaje amoroso. Pétronille Fanto, un ser andrógino de veintidós años que parece que tenga quince, una especialista en Christopher Marlowe con aspecto de poligonera, se convertirá con el tiempo en una escritora prolífica y, quizás, en un álter ego maligno de la misma Nothomb. La amistad etílica entre la escritora consagrada y la novel se transforma en duelo dialéctico, diversión, compañía y contraste..., pero también en un riesgo. Novela de inspiración autobiográfica, Pétronille es una ficción delirante y tremendamente divertida en la que hallamos algunos de los temas predilectos de la escritora belga: el protagonismo del cuerpo, la reflexión sobre la creación literaria y la sátira sobre la maquinaria editorial que la acompaña... Amélie Nothomb sumerge al lector en el estado de ebriedad entre ascético y alucinatorio del alcohol consumido en ayunas gracias a una prosa de una cosecha excelente en la que abundan el humor negro, la ironía y la genialidad estilística que la caracterizan. Puro oro líquido.",
    price: 20.00,
    image: "img/petronille.jpeg"
  }, 
  {
    id:14,
    title: "Lima subte",
    author: "Ernesto Carlín",
    editorial: "Altazor",
    category: "novela",
    category_display: "Novelas",
    status: "9/10",
    availability: "En stock",
    description: "Novela que recrea la escena del rock y la movida subterránea limeña, especialmente centrada en la figura de Leo Bacteria, líder de la banda Pestaña, y explora el contexto cultural, estético y social que rodeó a este movimiento contracultural a finales de los 80 y principios de los 90. ",
    price: 15.00,
    image: "img/lima_subte.jpeg"
  }, 
  {
    id:15,
    title: "Los funerales de mamá grande",
    author: "Gabriel García Márquez",
    editorial: "Grupo Norma",
    category: "cuento",
    category_display: "Cuentos",
    status: "9/10",
    availability: "En stock",
    description: "Bajo el lema de estos funerales mitológicos, Gabriel García Márquez reunió en 1962 siete relatos y la novela corta que da título al presente volumen, en el que aparece ya en todo su esplendor el elemento mágico y telúrico que a partir de entonces definiría su obra. Estamos en Macondo y su región una vez más, entre personajes y episodios reconocibles, pero ahora caen pájaros muertos sobre el poblado, rompiendo mosquiteros y alambradas, un cura ve al diablo o afirma haber encontrado al judío errante, y visitar la tumba de un ser querido supone un riesgo impredecible. Y hay que enterrar a la Mamá Grande, soberana absoluta de este mundo, que falleció en olor de santidad a los noventa y dos años, tras haber conservado la virginidad durante toda su vida, y a cuyos funerales acude el presidente de la República y hasta el Sumo Pontífice en su góndola papal, pero también guajiros, contrabandistas, arroceros, prostitutas, hechiceros y bananeros llegados para la ocasión. «Ésta es, incrédulos del mundo entero, la verídica historia de la Mamá Grande, soberana absoluta del reino de Macondo, que vivió en función de dominio durante 92 años y murió en olor de santidad un martes de septiembre pasado, y a cuyos funerales vino en Sumo Pontífice.»",
    price: 20.00,
    image: "img/los_funerales_de_mama_grande.jpeg"
  }, 
  {
    id:16,
    title: "Los testamentos traicionados",
    author: "Milan Kundera",
    editorial: "TusQuets",
    category: "ensayo",
    category_display: "Ensayos",
    status: "9/10",
    availability: "En stock",
    description: "Este ensayo está escrito como una novela : al filo de nueve partes independientes, los mismos personajes pasan y se cruzan: Stravinski y Kafka acompañados de sus peculiares amigos, Ernest Ansermet y Max Brod; Hemingway con su biógrafo; Leos Janacek con su pequeña nación; Rabelais con sus herederos: los grandes novelistas. Y eso porque el arte de la novela es la protagonista indiscutible de este libro: el espíritu del humor que lo engendró; su misterioso parentesco con la música; su historia, que evoluciona ( como la de la música) en tres tiempos; la estética de su tercer tiempo (el de la novela moderna); su sabiduría existencial. Es precisamente a la luz de esta «sabiduría de la novela» como examina en este libro las grandes situaciones de nuestra era: los procesos morales contra el arte del siglo, desde Céline hasta Maiakovski; el tiempo que pasa y hace que la identidad del «yo» presente se llene de incertidumbre con respecto al «yo» de ayer; el recuerdo como una forma de olvido; el pudor como noción esencial de una época basada en el individuo; la indiscreción que, convertida en regla y costumbre, anuncia el crepúsculo del individualismo; la fuerza misteriosa de la voluntad de un muerto; los testamentos; los testamentos traicionados (de Europa, del arte, del arte de la novela, de los artistas).",
    price: 30.00,
    image: "img/los_testamentos_traicionados.jpeg"
  }, 
  {
    id: 17,
    title: "Harry Potter y la cámara secreta. Harry Potter. 2",
    author: "Rowling, J. K.",
    editorial: "Salamandra",
    category: "fantasia",
    category_display: "Fantasía",
    status: "Usado- buenas condiciones",
    availability: "En stock",
    description: "Harry Potter y la cámara secreta, el segundo volumen de la ya clásica serie de novelas fantásticas de la autora británica J. K. Rowling. «Hay una conspiración, Harry Potter. Una conspiración para hacer que este año sucedan las cosas más terribles en el Colegio Hogwarts de Magia y Hechicería.» El verano de Harry Potter ha incluido el peor cumpleaños de su vida, las funestas advertencias de un elfo doméstico llamado Dobby y el rescate de casa de los Dursley protagonizado por su amigo Ron Weasley al volante de un coche mágico volador. De vuelta en el Colegio Hogwarts de Magia y Hechicería, donde va a empezar su segundo curso, Harry oye unos extraños susurros que resuenan por los pasillos vacíos. Y entonces empiezan los ataques y varios alumnos aparecen petrificados... Por lo visto, las siniestras predicciones de Dobby se están cumpliendo...",
    price: 30.00,
    image: "img/harry_camara.jpeg"
  }, 
  {
    id:18,
    title: "La Inmortalidad",
    author: "Milan Kundera",
    editorial: "TusQuets",
    category: "novela",
    category_display: "Novelas",
    status: "8.5/10",
    availability: "En stock",
    description: "A partir del gesto encantador de una mujer de cierta edad, el escritor crea el personaje de Agnes, alrededor de la cual aparecerán su hermana Laura, su marido Paul, y todo nuestro mundo contemporáneo en el que se rinde culto a la tecnología y la imagen. Pero ¿y si el hombre no fuera sino su imagen ?, pregunta otro personaje, Rubens, quien comprueba finalmente que de la más excitante de sus amantes sólo le quedan dos o tres fotografías mentales. Esta novela transforma todos los aspectos del mundo moderno en cuestiones metafísicas. Su forma es polifónica : las aventuras de los personajes imaginarios se mezclan con la historia de dos candidatos a la inmortalidad, Goethe y Bettina von Armin ; la reflexión sobre el nacimiento del homo senti-mentalis en la historia de Europa alterna con las peripecias parisienses del singular profesor Avenarius, para quien el mundo de hoy no sirve sino como objeto de juego. Kundera tiene el don de decir del modo más cristalino lo que a uno le resulta más difícil decirse, y en esta novela alcanza la cima de esta facultad.",
    price: 20.00,
    image: "img/inmortalidad.jpeg"
  }, 
  {
    id:19,
    title: "La Ilíada Contada a los Niños",
    author: "Rosa Navarro Durán",
    editorial: "Edebé",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Versión para niños de La Ilíada de Homero. La Ilíada nos cuenta lo que sucedió durante las últimas semanas de la guerra de Troya, en la que se enfrentaron griegos y troyanos. La ciudad de Troya se llamaba también Ilión, y por eso esta historia lleva el título de Ilíada. La Ilíada empieza con la furia del más grande de los héroes griegos, Aquiles, por la ofensa que le hizo el rey Agamenón. ¡Cuánto daño iba a causar! ¡Ven a descubrir este clásico de la historia de la literatura!",
    price: 40.00,
    image: "img/la_iliada.jpeg"
  }, 
  {
    id:20,
    title: "Moby Dick",
    author: "Herman Melville - adaptación de Geraldine McCaughrean",
    editorial: "Vicen Vives",
    category: "planlector",
    category_display: "Plan lector",
    status: "Usado- buenas condiciones",
    availability: "En stock",
    description: "El capitán Ahab se echa a los mares para dar muerte a Moby Dick, el gran cachalote blanco que le arrebató una pierna. La delirante obsesión del viejo lobo de mar, que identifica a la ballena con todos sus males físicos y sus dudas existenciales, arrastrará consigo a la mayor parte de la tripulación del «Pequod». En esta vibrante adaptación de Moby Dick, Geraldine McCaughrean recrea la trama de una novela subyugadora que nos previene contra el orgullo desmedido y el ejercicio irresponsable del poder.",
    price: 45.00,
    image: "img/moby_dick.jpg"
  }, 
  {
    id:21,
    title: "Muerte en el pentagonito",
    author: "Ricardo Uceda",
    editorial: "Planeta",
    category: "novela",
    category_display: "Novelas",
    status: "9/10",
    availability: "En stock",
    description: "Los secretos militares de la lucha antiterrorista en el Perú son revelados por primera vez en una narración espeluznante, en la que se transporta sin tregua al lector por dos décadas de crímenes y atrocidades, en un viaje por los temidos pasadizos de los servicios de inteligencia. Luego de más de siete años de investigación, su autor ofrece revelaciones de extraordinario impacto. Y no sólo porque esclarecen asesinatos emblemáticos, sino, sobre todo, porque descubren otras muertes desconocidas hasta hoy, cometidas en la mismísima sede del cuartel general del Ejército del Perú, conocido comúnmente como el Pentagonito.",
    price: 40.00,
    image: "img/muerte_en_el.jpg"
  }, 
  {
    id:22,
    title: "Ébano",
    author: "Ryszard Kapuscinski",
    editorial: "Anagrama",
    category: "cronica",
    category_display: "Crónicas",
    status: "10/10",
    availability: "En stock",
    description: "Quien muchos consideran el mejor reportero del siglo se sumerge en el continente africano, rehuyendo lugares comunes y estereotipos. Vive en las casas repletas de cucarachas de los más pobres, enferma de malaria cerebral, corre peligro de muerte a manos de un guerrillero& . pero pese a todo no pierde su mirada lúcida y su voz de gran narrador para adentrar al lector en la compleja realidad de África, con las guerras, miseria e injusticia que atraviesan su historia y lastran su presente. Posiblemente la obra cumbre del autor, ganadora del Premio Viareggio, entre otros galardones.",
    price: 40.00,
    image: "img/ebano.jpg"
  }, 
  {
    id:23,
    title: "Otras voces, otros ámbitos",
    author: "Truman Capote",
    editorial: "Anagrama",
    category: "novela",
    category_display: "Novelas",
    status: "Usado- buenas condiciones",
    availability: "En stock",
    description: "Otras voces, otros ámbitos fue el deslumbrante debut de un jovencísimo Truman Capote. Una novela en la que nos mete «en los laberintos que sólo ofrece una literatura de alto voltaje» (Carmen Martín Gaite), con un universo mórbido e inquietante y unas vívidas e inesperadas imágenes de extraordinaria belleza.Es la historia de un hijo que busca a su padre, de un joven en busca de su identidad. Un muchacho de trece años, Joel Knox, a la muerte de su madre en Nueva Orleans, es enviado a casa de su padre, a quien jamás conoció. En una ruinosa mansión de una aislada plantación en el profundo Sur viven, con el padre de Joel, su madrastra, Miss Amy, el misterioso primo Randolph personaje capital de la novela y la criada, la negrita Missouri. Los escasos vecinos son personajes estrambóticos, fuera de lo común: las gemelas Idabel y Florabel, el diminuto centenario Jesús Fever, su nieta Zoo apuñalada por su novio el día de la boda y Little Sunshine, el negro ermitaño. Finalmente, Joel conoce a su padre y se siente decepcionado, atrapado; pretende huir de este extraño universo hasta que descubre, de pronto, el sentido de los dramas que rodeaban su infancia.",
    price: 45.00,
    image: "img/otras_voces.jpg"
  },  
  {
    id:24,
    title: "Templado",
    author: "Jorge Eslava",
    editorial: "Loqueleo",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Un profesor encuentra el diario inconcluso de un estudiante desaparecido y decide publicarlo como un reconocimiento a todos los jóvenes que sufren por amor. Permite trabajar el tema del primer amor en los adolescentes. Propicia el análisis de las actitudes humanas",
    price: 20.00,
    image: "img/templado.jpg"
  },  
  {
    id:25,
    title: "El club de la limonada",
    author: "María Fernanda Heredia",
    editorial: "Loqueleo",
    category: "planlector",
    category_display: "Plan lector",
    status: "9/10",
    availability: "En stock",
    description: "Tres amigos, ante su mala suerte en el amor, fundan el Club Limonada. Se trata de un divertido lugar para desahogarse, reír y elaborar una larga lista negra de los “medios limones”. Propicia la conversación sobre el tema del amor y las relaciones interpersonales.",
    price: 35.00,
    image: "img/el_club_de_la_limonada.jpg"
  }, 
  {
    id: 26,
    title: "La historia de Don Quijote de la Mancha",
    author: "Miguel de Cervantes Saavedra",
    editorial: "Panamericana",
    category: "planlector",
    category_display: "Plan lector",
    status: "10/10",
    availability: "En stock",
    description: "Con un lenguaje sencillo y dividida en cortos capítulos, acompañados de divertidas y coloridas ilustraciones, esta novela, que es una adaptación del gran clásico de la literatura, está pensada para atrapar a los jóvenes lectores en el maravilloso mundo de don Quijote y su fiel escudero, Sancho Panza.",
    price: 40.00,
    image: "img/la_historia_de_don_quijote.jpg"
  },
  {
    id: 27,
    title: "¡Ay, cuánto me quiero!",
    author: "Mauricio Paredes",
    editorial: "Santillana",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Un niño se ama tanto que siente que todo aquello que lo rodea existe para complacerlo. Un día, conoce a una niña tímida que lo ayuda a no pensar solo en sí mismo. Promueve la amistad y la ayuda mutua.",
    price: 20.00,
    image: "img/ay_cuanto_me_quiero.jpg"
  },
  {
    id: 28,
    title: "Nuestro planeta, Natacha",
    author: "Luis María Pescetti",
    editorial: "Loqueleo",
    category: "planlector",
    category_display: "Plan lector",
    status: "9/10",
    availability: "En stock",
    description: "La protagonista, Natacha, y su amiga Pati, junto a sus compañeros, realizan un proyecto anual sobre cómo cuidar el planeta y a la humanidad, interactuando con chicos de otra escuela y enfrentando desafíos de amistad y cooperación para lograr su objetivo común de cuidar el planeta",
    price: 35.00,
    image: "img/nuestro_planeta_natacha.jpg"
  },
  {
    id: 29,
    title: "El misterio de la biblioteca más pequeña del mundo",
    author: "Miguel Mendonza Luna",
    editorial: "Panamericana",
    category: "planlector",
    category_display: "Plan lector",
    status: "9/10",
    availability: "En stock",
    description: "En la biblioteca más pequeña del mundo la bibliotecaria Clara Clarisa, con solo mirarte, puede recetarte un libro que cambiará tu vida. Hasta este mágico lugar llegan tres misteriosos personajes que parecen buscar algo más que un libro. Ramona Ramones y Guido Guirnaldo, dos inteligentes jóvenes que aman los libros, sospechan que algo ocultan este trío de siniestros e inusuales visitantes. Al parecer, un importante robo se relaciona con la presencia de los sospechosos en la biblioteca.",
    price: 30.00,
    image: "img/el_misterio_de_la_biblioteca.jpg"
  },
  {
    id: 30,
    title: "Alma y Frin",
    author: "Luis María Pescetti",
    editorial: "Loqueleo",
    category: "planlector",
    category_display: "Plan lector",
    status: "9/10",
    availability: "En stock",
    description: "Un nuevo episodio en la vida del querido Frin y su grupo de amigos. Comienzan las vacaciones y Frin visita el campo de su tío, mientras Alma está en la playa con su mamá y Lynko conoce Alemania, el lugar donde podría llegar a vivir. Cada uno vive el verano como un comienzo nuevo, como una forma nueva de sentirse en el mundo. Y en el medio, habrá un caso policial, muchos partidos de fútbol y una noche de fiesta imperdible.",
    price: 35.00,
    image: "img/alma_y_frin.jpg"
  },
  {
    id: 31,
    title: "Voy a salir jalado en Castellano",
    author: "Lorenzo Helguero",
    editorial: "Santilla",
    category: "planlector",
    category_display: "Plan lector",
    status: "Usado- buenas condiciones",
    availability: "En stock",
    description: "Mario Darío es un estudiante que odia leer, odia el curso de Castellano y odia su nombre. Él no desperdicia la oportunidad de fastidiar al profesor Arosemena, su profesor de Castellano, a pesar de que cada vez que lanza en clase alguna respuesta jocosa, el maestro le encarga una tarea de Castellano y Literatura. De esta manera, y de manera involuntaria, Arosemena se convierte en el detonador de diferentes situaciones que involucran a Mario: el desafío académico, la relación con su familia y, por supuesto, el amor. Mario Darío, que al principio dice odiar todo lo relacionado a la Lengua y la Literatura, termina escribiendo un diario y versos de amor.",
    price: 33.00,
    image: "img/voy_a_salir_jalado.jpg"
  },
  {
    id: 32,
    title: "Cuando callaron las armas",
    author: "Edna Iturralde",
    editorial: "Grupo Norma",
      category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Doce relatos asombrosos y humanos que hablan sobre la vida cotidiana de niños que viven en medio de graves conflictos armados en distintos lugares del mundo. Estas historias sobre Israel y Palestina, Afganistán, Colombia, Chechenia, Bosnia, Liberia, Sudán, Ruanda, Irlanda del Norte, Irak, Sri Lanka y España conforman un libro conmovedor y sin precedentes en la literatura infantil latinoamericana. Un libro para crear conciencia e interesar a los lectores en cómo los niños viven la violencia, y la importancia de hacer cumplir los derechos humanos.",
    price: 28.00,
    image: "img/cuando_callaron_las_armas.jpg"
  },
  {
    id: 33,
    title: "Dioses y héroes de la mitología griega",
    author: "Ana Maria Shua",
    editorial: "Santillana",
    category: "planlector",
    category_display: "Plan lector",
    status: "9/10",
    availability: "En stock",
    description: "Ana María Shua narra con un estilo magistral los relatos míticos más bellos. Héroes y dioses que deberán luchar contra terribles monstruos y, sobre todo, contra su propio destino. Relatos breves que explican el origen de los seres mitológicos griegos. Propician el análisis de actitudes. Los mitos griegos han permanecido vigentes a través de los siglos.",
    price: 28.00,
    image: "img/dioses_y_heroes_de_la_mitologia_griega.jpeg"
  },
  {
    id: 37,
    title: "Paco Yunque / El vencedor",
    author: "César Vallejo",
    editorial: "Loqueleo",
    category: "novela",
    category_display: "Novelas",
    status: "8.5/10",
    availability: "En stock",
    description: "Dos extraordinarios cuentos. Paco Yunque narra la historia de un niño campesino que es llevado a la ciudad para acompañar al hijo del hombre más poderoso del pueblo. El vencedor recrea la pelea entre dos escolares después de clases. La narración presenta, además de la pelea, las reacciones y sentimientos de los demás ante esta situación.",
    price: 30.00,
    image: "img/paco_yunque_el_vencedor.jpeg"
  },
  {
    id: 38,
    title: "¡Quita esas patas, caraqueso!",
    author: "Geronimo Stilton",
    editorial: "Fondo de Cultura Económica",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Una historia inmortal sobre la muerte, el amor y la soledad, ambientada en el pueblo fantasma de Comala.",
    price: 8.00,
    image: "img/quita_esas_patas_caraqueso.jpeg"
  },
  {
    id: 39,
    title: "Palabras de Caramelo",
    author: "Gonzalo Moure",
    editorial: "Fondo de Cultura Económica",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "Una historia inmortal sobre la muerte, el amor y la soledad, ambientada en el pueblo fantasma de Comala.",
    price: 15.00,
    image: "img/palabras_de_caramelo.jpg"
  },
  {
    id: 40,
    title: "La rebelion de las palabras",
    author: "Andrea Ferrari",
    editorial: "Santillana",
    category: "novela",
    category_display: "Novelas",
    status: "8/10",
    availability: "En stock",
    description: "Una historia inmortal sobre la muerte, el amor y la soledad, ambientada en el pueblo fantasma de Comala.",
    price: 12.00,
    image: "img/la_rebelion_de_las.jpeg"
  },
  {
    id: 41,
    title: "El misterio del cementerio viejo",
    author: "Fina Casalderrey",
    editorial: "Ediciones SM",
    category: "planlector",
    category_display: "Plan lector",
    status: "8/10",
    availability: "En stock",
    description: "David y Blanca oyen voces que vienen del cementerio. Están convencidos de que son las almas de los muertos las que hablan. Deciden ir allí a investigar y a ver algún alma. Aunque les da algo de miedo que una de esas almas les aprese, van al cementerio varias noches. Siguiendo la dirección de las voces, que les llaman por su nombre, se meten en un túnel lleno de ratas. Pese al asco que les da, deciden seguir adelante. Encuentran un hueco en el techo y, al sacar por él la cabeza, se encuentran en la taberna. Caso resuelto: por debajo del cementerio pasan unos tubos de cemento que se comunican con la taberna y a través de los cuales se transmiten las voces. Los niños vuelven a casa contentos por haber recuperado la tranquilidad.",
    price: 15.00,
    image: "img/el_misterio_del_cementerio_viejo.jpeg"
  },
  {
    id:42,
    title: "Conejo de Pascua y su ejército en el centro de la tierra",
    author: "William Joyce",
    editorial: "Bambu",
    category: "fantasia",
    category_display: "Fantasía",
    status: "7/10",
    availability: "En stock",
    description: "Sombra, el Rey de las pesadillas, y su ejército de temores fueron derrotados en el primer episodio de las aventuras de los Guardianes. Parece que ahora el malvado enemigo de los niños está urdiendo una terrible venganza, y los Guardianes sospechan que se ha escondido bajo tierra. Pero, si es así ¿cómo van a encontrarlo? Aquí entra en escena Conejo de Pascua, Bunny para los amigos, el único emisario de la legendaria hermandad de conejos guerreros de tamaño e intelecto imponentes. Bunny domina las artes marciales y es brillante, sagaz y un excavador de túneles extraordinario. Cuenta también con la ayuda de unos soldados muy especiales. ¿Conseguirán los Guardianes dar con Sombra y desbaratar sus crueles planes de venganza?",
    price: 38.00,
    image: "img/conejo_de_pascua.jpeg"
  }, 
  {
    id:43,
    title: "Sendero. Historia de la guerra milenaria en el Perú",
    author: "Gustavo Gorriti",
    editorial: "Planeta",
    category: "periodismo",
    category_display: "Periodismo de investigación",
    status: "8.5/10",
    availability: "En stock",
    description: "Ningún conflicto armado ha estremecido al Perú tanto como el que provocó Sendero Luminoso: casi setenta mil peruanos muertos en la peor década de violencia interna de la que el país tiene registro. Sendero es un libro extraordinario, que revela y esclarece cómo se gestó una de las insurrecciones a la vez más letales y misteriosas en América Latina. Con un brillante trabajo que combina el periodismo de investigación y la historiografía de guerra, Gorriti descubre los orígenes de la violencia senderista y escribe esta historia imprescindible para entender el Perú, durante el período mismo de la guerra. Publicado por primera vez en 1990, Sendero alumbró mediante la profusión de documentos y la precisión al detalle, lograda a través de años de cobertura y centenares de entrevistas, a los personajes, los guiones y los hechos de una lucha interna que destruía desde las sombras.En la historia de las insurrecciones armadas, pocos libros han descrito con tanta precisión su complejo inicio: Cuando una organización violenta, en apariencia extraña y ajena al continente y al momento histórico, fuerza su presencia sobre una sociedad renuente, una democracia precaria y un Estado contradictorio. Años después de su primera edición, este libro se ha convertido en la referencia fundamental para entender la génesis de la violencia en un país de América latina que, como muchos otros, aún padece de una inmensa fractura social.",
    price: 30.00,
    image: "img/sendero_historia_de_la_guerra_milenaria_en_el_peru.jpeg"
  }, 
  {
    id:44,
    title: "Ojos de perro azul",
    author: "Gabriel García Márquez",
    editorial: "Grupo Norma",
    category: "cuento",
    category_display: "Cuentos",
    price: 25.00,
    image: "img/ojos_de_perro_azul.jpeg"
  }, 
  {
    id:45,
    title: "Mitad monjes, mitad soldados",
    author: "Pedro Salinas ",
    editorial: "Planeta",
    category: "periodismo",
    category_display: "Periodismo de investigación",
    price: 35.00,
    image: "img/mitad_monjes_mitad_soldados.jpeg"
  }, 
  {
    id:46,
    title: "El otoño del patriarca",
    author: "Gabriel García Márquez",
    editorial: "Grupo Norma",
    category: "novela",
    category_display: "Novelas",
    price: 25.00,
    image: "img/el_otoño_del_patriarca.jpeg"
  }, 
  {
    id:47,
    title: "El quinto dragón ",
    author: "Paulina Aguilar",
    editorial: "Grupo Norma",
    category: "novela",
    category_display: "Novelas",
    price: 35.00,
    image: "img/el_quinto_dragon.jpeg"
  }, 
  {
    id:48,
    title: "La broma",
    author: "Milan Kundera",
    editorial: "Maxi Tusquets",
    category: "novela",
    category_display: "Novelas",
    price: 30.00,
    image: "img/la_broma.jpeg"
  }, 
  {
    id:49,
    title: "Un misterio, una pasión",
    author: "Aldo Miyashiro",
    category: "ficcion",
    category_display: "Ficción",
    price: 20.00,
    image: "img/un misterio.jpeg"
  }, 
  {
    id:50,
    title: "Yo nunca digo adiós",
    author: "Maria Fernanda Heredia",
    category: "planlector",
    category_display: "Plan lector",
    price: 27.00,
    image: "img/yo_nunca_digo_adios.jpeg"
  }, 
  {
    id:51,
    title: "Crónica de una muerte anunciada",
    author: "Gabriel García Márquez",
    category: "novela",
    category_display: "Novelas",
    price: 15.00,
    image: "img/cronica_muerte_anunciada.jpeg"
  }, 
  {
    id:52,
    title: "Mitología romana",
    author: "Florence Noiville",
    category: "cuento",
    category_display: "Cuentoss",
    price: 28.00,
    image: "img/mitologia_romana.jpeg"
  }, 
  {
    id:53,
    title: "Charlie y la fabrica de chocolate",
    author: "Roald Dahl",
    category: "planlector",
    category_display: "Plan lector",
    price: 32.00,
    image: "img/charlie_y_la_fabrica_de_chocolate.jpeg"
  }, 
  {
    id:54,
    title: "El viejo y el mar",
    author: "Ernest Hemingay",
    category: "novela",
    category_display: "Novelas",
    price: 20.00,
    image: "img/el_viejo_y_el_mar.jpeg"
  }, 
  {
    id:55,
    title: "Jakob Von Gunten",
    author: "Robert Walser",
    category: "novela",
    category_display: "Novelas",
    price: 30.00,
    image: "img/jakob_von_gunten.jpeg"
  }, 
  {
    id:56,
    title: "La lentitud",
    author: "Milan Kundera",
    category: "novela",
    category_display: "Novelas",
    status: "9.5/10",
    availability: "En stock",
    price: 30.00,
    image: "img/la_lentitud.jpeg"
  }, 
  {
    id:57,
    title: "Amigos robots",
    author: "Isaac Asimov",
    category: "planlector",
    category_display: "Plan lector",
    price: 25.00,
    image: "img/amigos_robot.jpg"
  }, 
  {
    id:58,
    title: "Animales extremos",
    author: "Nicola Davies",
    category: "planlector",
    category_display: "Plan lector",
    price: 40.00,
    image: "img/animales_extremos.jpeg"
  }, 
  {
    id:59,
    title: "Wigetta y los gusanos guasones",
    author: "Vegetta777 & Willyrex",
    category: "cuento",
    category_display: "Cuentos",
    price: 30.00,
    image: "img/wigetta_y_los_gusanos_guasones.jpg"
  }, 
  {
    id:60,
    title: "Viajes con Heródoto",
    author: "Ryszard Kapuscinski",
    category: "novela",
    category_display: "Novelas",
    price: 30.00,
    image: "img/viajes_con_herodoto.jpeg"
  }, 

  {
    id:62,
    title: "Tradiciones peruanas. Tomo I",
    author: "Ricardo Palma",
    category: "cuento",
    category_display: "Cuentos",
    price: 20.00,
    image: "img/tradiciones_peruanas_tomo1.jpeg"
  }, 
  {
    id:63,
    title: "Tiempo transcurrido",
    author: "Juan Villoro",
    category: "novela",
    category_display: "Novelas",
    price: 40.00,
    image: "img/tiempo_transcurrido.jpg"
  }, 
  {
    id:64,
    title: "Quebradura. Breviario de viajes de la Amazonía",
    author: "Miguel Donayre",
    category: "ficcion",
    category_display: "Ficción",
    price: 20.00,
    image: "img/quebradura_breviario_de_viajes.jpg"
  }, 
  {
    id:65,
    title: "Sombras de un rescate",
    author: "David Hidalgo",
    category: "periodismoycomunicacion",
    category_display: "Periodismo y comunicación",
    price: 25.00,
    image: "img/sombras_de_un_rescate.jpg"
  }, 
  {
    id:66,
    title: "Relatos Mágicos del Perú 3",
    author: "Javier Zapata Innocenzi",
    category: "cuento",
    category_display: "Cuentos",
    price: 25.00,
    image: "img/relatos_magicos_del_peru_3.jpg"
  }, 
  {
    id:67,
    title: "Relatos Mágicos del Perú",
    author: "Javier Zapata Innocenzi",
    category: "cuento",
    category_display: "Cuentos",
    price: 25.00,
    image: "img/relatos_magicos_del_peru.jpg"
  }, 
{
    id:68,
    title: "Libro las crónicas de Narnia 3: El caballo y el muchacho",
    author: "Javier Zapata Innocenzi",
    category: "ficcion",
    category_display: "Ficción",
    price: 25.00,
    image: "img/narnia_el_caballo_y_el_muchacho.jpg"
  }, 
  {
    id:69,
    title: "La gaviota / El jardín de los cerezos",
    author: "Antón Chéjov",
    category: "novela",
    category_display: "Novelas",
    price: 20.00,
    image: "img/la_gaviota.jpeg"
  }, 
  {
    id:70,
    title: "La guerra de los mundos",
    author: "H.G. Wells",
    category: "novela",
    category_display: "Novelas",
    price: 25.00,
    image: "img/la_guerra_de_los.jpg"
  }, 
  {
    id:71,
    title: "La verdad sobre el caso Harry Quebert",
    author: "Joel Dicker",
    category: "novela",
    category_display: "Novelas",
    price: 20.00,
    image: "img/la_verdad_sobre.jpg"
  }, 
  {
    id:72,
    title: "Nuevos relatos mágicos 1",
    author: "Javier Zapata Innocenzi",
    category: "cuento",
    category_display: "Cuentos",
    price: 25.00,
    image: "img/nuevos_relatos_magicos_del_peru1.jpg"
  }, 
  {
    id:73,
    title: "Cuentos completos 1",
    author: "Ezequiel Martínez Estrada",
    category: "cuento",
    category_display: "Cuentos",
    price: 60.00,
    image: "img/cuentos_completos.jpeg"
  }, 
  {
    id:74,
    title: "CRONOS: diccionario filosófico",
    author: "Varios autores",
    category: "historia",
    category_display: "Historia",
    price: 30.00,
    image: "img/diccionario_filosofico.jpg"
  }, 
  {
    id:75,
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes",
    category: "planlector",
    category_display: "Plan lector",
    price: 60.00,
    image: "img/don_quijote_de_la_mancha.jpg"
  }, 
  {
    id:76,
    title: "Efecto invernadero / Canon perpetuo",
    author: "Mario Bellatin",
    category: "novela",
    category_display: "Novelas",
    price: 20.00,
    image: "img/efecto_invernadero.jpg"
  }, 
  {
    id:77,
    title: "El Acertijo del papiro real de Turín",
    author: "Maria Mañeru",
    category: "novelainfantil",
    category_display: "Novela infantil",
    price: 40.00,
    image: "img/el_acertijo_del_papiro_real_de_turin.jpg"
  }, 
  {
    id:78,
    title: "En sus trece. Prensa que irrita al poder (2011-2018)",
    author: "César Hildebrandt",
    category: "periodismoycomunicacion",
    category_display: "Periodismo y comunicación",
    price: 25.00,
    image: "img/en_sus_trece.jpg"
  }, 
  {
    id:79,
    title: "Abimael. El sendero del terror",
    author: "Umberto Jara",
    category: "periodismo",
    category_display: "Periodismo de investigación",
    price: 30.00,
    image: "img/el_sendero_del.jpg"
  }, 
  {
    id:80,
    title: "Historia de la corrupción en el Perú",
    author: "Alfonso W. Quiroz",
    category: "historia",
    category_display: "Historia",
    price: 30.00,
    image: "img/historia_de_la_corrupción_en_el_peru.jpg"
  }, 
  {
    id:81,
    title: "Mitos griegos",
    author: "María. Angelidou",
    category: "planlector",
    category_display: "¨Plan lector",
    price: 35.00,
    image: "img/mitos_griegos.jpg"
  }, 
  {
    id:82,
    title: "Mitos griegos: Los viajes de Odiseo",
    author: "Sue Reid",
    category: "planlector",
    category_display: "¨Plan lector",
    price: 35.00,
    image: "img/mitos_griegos_los_viajes_de_odiseo.jpg"
  }, 
  {
    id:83,
    title: "Mi planta de naranja lima",
    author: "Jose Mauro de Vasconcelos",
    category: "novela",
    category_display: "¨Novelas",
    price: 25.00,
    image: "img/mi_planta_de_naranja_lima.jpeg"
  }, 
  {
    id:84,
    title: "Manuel D´Ornellas. Una antología de sus artículos",
    author: "Manuel D´Ornellas",
    category: "periodismoycomunicacion",
    category_display: "¨Periodismo y comunicación",
    price: 35.00,
    image: "img/manuel_dornellas_una_antologia_de_sus_articulos.jpg"
  }, 
  {
    id:85,
    title: "El Fantasma de Canterville y otros cuentos",
    author: "Oscar Wilde",
    category: "planlector",
    category_display: "Plan lector",
    price: 20.00,
    image: "img/el_fantasma_de_canterville.jpg"
  }, 
  {
    id:86,
    title: "Genaro",
    author: "Hugo coya",
    category: "periodismoycomunicacion",
    category_display: "Periodismo y comunicación",
    price: 10.00,
    image: "img/genaro.jpg"
  },
  {
    id:87,
    title: "Los ejércitos de la noche",
    author: "Norman Mailer",
    category: "novela",
    category_display: "¨Novelas",
    price: 30.00,
    image: "img/ejercitos_noche.jpg"
  },
  {
    id:88,
    title: "El sueño del celta",
    author: "Mario Vargas Llosa",
    category: "novela",
    category_display: "Novelas",
    price: 35.00,
    image: "img/el_sueño_del.jpg"
  }, 
  {
    id:89,
    title: "La distancia que nos separa",
    author: "Renato Cisneros",
    category: "novela",
    category_display: "Novelas",
    price: 40.00,
    image: "img/la_distancia_que.jpg"
  }, 
  {
    id:89,
    title: "La estrella del reportero",
    author: "Ivan Slocovich",
    category: "periodismoycomunicacion",
    category_display: "Periodismo y comunicación",
    price: 15.00,
    image: "img/la_estrella_del_reportero.jpg"
  }, 
  {
    id:89,
    title: "La china Tudela y la Panaca Real",
    author: "Rafo León",
    category: "ficcion",
    category_display: "Ficción",
    price: 15.00,
    image: "img/la_china_tudela_y_la_panaca_real.jpg"
  },
  {
    id:89,
    title: "La fiesta de la insignificancia",
    author: "Milan Kundera",
    category: "ficcion",
    category_display: "Ficción",
    price: 20.00,
    image: "img/la_fiesta_de_la_insignificancia.jpg"
  }, 
];